#!/usr/bin/env bash
# Setups the repository

container install

# Stop on errors
set -e

cd "$(dirname "$0")/.."

echo "Installing development dependencies..."
python3 -m pip install pre-commit

pre-commit install
python3 -m pip install -r requirements_dev.txt