name: Build

on:
  push:
    branches:
      - master
      - dev

jobs:
  validate:
    runs-on: "ubuntu-latest"
    name: Validate HACS
    steps:
      - uses: "actions/checkout@v2"

      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
          ignore: topics

      - name: Hassfest validation
        uses: "home-assistant/actions/hassfest@master"

  style:
    runs-on: "ubuntu-latest"
    name: Check style formatting
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2.3.1"
        with:
          python-version: "3.x"
      - run: python3 -m pip install black
      - run: black .
      - run: python3 -m pip install isort
      - run: isort .

  lint-isort:
    name: Check isort
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v2.4.0
      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v2.3.1
        id: python
        with:
          python-version: "3.x"
      - name: Restore pre-commit environment from cache
        id: cache-precommit
        uses: actions/cache@v2.1.7
        with:
          path: ${{ env.PRE_COMMIT_CACHE }}
          key: ${{ runner.os }}-${{ needs.prepare-base.outputs.pre-commit-key }}
      - name: Setup pre-commit
      - run: |
          python3 -m pip install pre-commit
          pre-commit install
      - name: Run isort
        run: pre-commit run --hook-stage manual isort --all-files --show-diff-on-failure

  tests:
    runs-on: "ubuntu-latest"
    name: Run tests
    steps:
      - name: Check out code from GitHub
        uses: "actions/checkout@v2"
      - name: Setup Python
        uses: "actions/setup-python@v2.3.1"
        with:
          python-version: "3.8"
      - name: Install requirements
        run: python3 -m pip install -r requirements_test.txt
      - name: Run tests
        run: |
          pytest \
            -qq \
            --timeout=9 \
            --durations=10 \
            -n auto \
            --cov custom_components.nefiteasy \
            -o console_output_style=count \
            -p no:sugar \
            tests
